[2022-05-24 02:19:51 +0800] [92007] [INFO] Starting gunicorn 20.0.4
[2022-05-24 02:19:51 +0800] [92007] [INFO] Listening at: http://0.0.0.0:9004 (92007)
[2022-05-24 02:19:51 +0800] [92007] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-05-24 02:19:51 +0800] [92010] [INFO] Booting worker with pid: 92010
[2022-05-24 02:19:51 +0800] [92011] [INFO] Booting worker with pid: 92011
[2022-05-24 02:19:51 +0800] [92012] [INFO] Booting worker with pid: 92012
[2022-05-24 02:19:51 +0800] [92013] [INFO] Booting worker with pid: 92013
[2022-05-24 02:19:51 +0800] [92014] [INFO] Booting worker with pid: 92014
[2022-05-24 02:19:51 +0800] [92015] [INFO] Booting worker with pid: 92015
[2022-05-24 02:19:51 +0800] [92016] [INFO] Booting worker with pid: 92016
[2022-05-24 02:19:51 +0800] [92023] [INFO] Booting worker with pid: 92023
[2022-05-24 02:19:51 +0800] [92024] [INFO] Booting worker with pid: 92024
[2022-05-24 02:19:51 +0800] [92025] [INFO] Booting worker with pid: 92025
[2022-05-24 02:19:52 +0800] [92026] [INFO] Booting worker with pid: 92026
[2022-05-24 02:19:52 +0800] [92027] [INFO] Booting worker with pid: 92027
[2022-05-24 02:19:52 +0800] [92028] [INFO] Booting worker with pid: 92028
[2022-05-24 02:19:52 +0800] [92029] [INFO] Booting worker with pid: 92029
[2022-05-24 02:19:52 +0800] [92030] [INFO] Booting worker with pid: 92030
[2022-05-24 02:19:52 +0800] [92031] [INFO] Booting worker with pid: 92031
[2022-05-24 02:19:52 +0800] [92032] [INFO] Booting worker with pid: 92032
[2022-05-24 02:19:52 +0800] [92034] [INFO] Booting worker with pid: 92034
[2022-05-24 02:19:52 +0800] [92036] [INFO] Booting worker with pid: 92036
[2022-05-24 02:19:52 +0800] [92037] [INFO] Booting worker with pid: 92037
[2022-05-24 02:19:52 +0800] [92038] [INFO] Booting worker with pid: 92038
[2022-05-24 02:19:52 +0800] [92039] [INFO] Booting worker with pid: 92039
[2022-05-24 02:19:52 +0800] [92040] [INFO] Booting worker with pid: 92040
[2022-05-24 02:19:52 +0800] [92041] [INFO] Booting worker with pid: 92041
[2022-05-24 02:19:52 +0800] [92042] [INFO] Booting worker with pid: 92042
[2022-05-24 02:20:04 +0800] [92016] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92026] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92034] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92012] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92027] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92032] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92013] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92026] [INFO] Worker exiting (pid: 92026)
[2022-05-24 02:20:04 +0800] [92012] [INFO] Worker exiting (pid: 92012)
[2022-05-24 02:20:04 +0800] [92016] [INFO] Worker exiting (pid: 92016)
[2022-05-24 02:20:04 +0800] [92034] [INFO] Worker exiting (pid: 92034)
[2022-05-24 02:20:04 +0800] [92013] [INFO] Worker exiting (pid: 92013)
[2022-05-24 02:20:04 +0800] [92032] [INFO] Worker exiting (pid: 92032)
[2022-05-24 02:20:04 +0800] [92027] [INFO] Worker exiting (pid: 92027)
[2022-05-24 02:20:04 +0800] [92010] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92010] [INFO] Worker exiting (pid: 92010)
[2022-05-24 02:20:04 +0800] [92042] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92042] [INFO] Worker exiting (pid: 92042)
[2022-05-24 02:20:04 +0800] [92011] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92011] [INFO] Worker exiting (pid: 92011)
[2022-05-24 02:20:04 +0800] [92023] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92023] [INFO] Worker exiting (pid: 92023)
[2022-05-24 02:20:04 +0800] [92037] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92037] [INFO] Worker exiting (pid: 92037)
[2022-05-24 02:20:04 +0800] [92029] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92029] [INFO] Worker exiting (pid: 92029)
[2022-05-24 02:20:04 +0800] [92036] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92036] [INFO] Worker exiting (pid: 92036)
[2022-05-24 02:20:04 +0800] [92040] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92038] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92040] [INFO] Worker exiting (pid: 92040)
[2022-05-24 02:20:04 +0800] [92038] [INFO] Worker exiting (pid: 92038)
[2022-05-24 02:20:04 +0800] [92041] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92041] [INFO] Worker exiting (pid: 92041)
[2022-05-24 02:20:04 +0800] [92014] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92014] [INFO] Worker exiting (pid: 92014)
[2022-05-24 02:20:04 +0800] [92028] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92028] [INFO] Worker exiting (pid: 92028)
[2022-05-24 02:20:04 +0800] [92025] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92025] [INFO] Worker exiting (pid: 92025)
[2022-05-24 02:20:04 +0800] [92030] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92030] [INFO] Worker exiting (pid: 92030)
[2022-05-24 02:20:04 +0800] [92031] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92015] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92031] [INFO] Worker exiting (pid: 92031)
[2022-05-24 02:20:04 +0800] [92015] [INFO] Worker exiting (pid: 92015)
[2022-05-24 02:20:04 +0800] [92039] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:04 +0800] [92039] [INFO] Worker exiting (pid: 92039)
[2022-05-24 02:20:04 +0800] [92024] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/main.py", line 9, in <module>
    from app import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/__init__.py", line 8, in <module>
    from .api import create_app
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/api.py", line 11, in <module>
    from .routers import risk_router_init
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/__init__.py", line 8, in <module>
    from .ml_router import ml_router
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 11, in <module>
    from app.app.v4.core.inputs import InputData
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 14, in <module>
    class AppList(BaseModel):
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/core/inputs.py", line 16, in AppList
    appName: str = Field(title='APP名', description='app名称,原始值')
TypeError: Field() missing 1 required positional argument: 'default'
[2022-05-24 02:20:05 +0800] [92024] [INFO] Worker exiting (pid: 92024)
[2022-05-24 02:27:23 +0800] [92253] [INFO] Starting gunicorn 20.0.4
[2022-05-24 02:27:23 +0800] [92253] [INFO] Listening at: http://0.0.0.0:9004 (92253)
[2022-05-24 02:27:23 +0800] [92253] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-05-24 02:27:23 +0800] [92256] [INFO] Booting worker with pid: 92256
[2022-05-24 02:27:23 +0800] [92257] [INFO] Booting worker with pid: 92257
[2022-05-24 02:27:23 +0800] [92258] [INFO] Booting worker with pid: 92258
[2022-05-24 02:27:23 +0800] [92259] [INFO] Booting worker with pid: 92259
[2022-05-24 02:27:23 +0800] [92260] [INFO] Booting worker with pid: 92260
[2022-05-24 02:27:23 +0800] [92261] [INFO] Booting worker with pid: 92261
[2022-05-24 02:27:23 +0800] [92262] [INFO] Booting worker with pid: 92262
[2022-05-24 02:27:24 +0800] [92263] [INFO] Booting worker with pid: 92263
[2022-05-24 02:27:24 +0800] [92264] [INFO] Booting worker with pid: 92264
[2022-05-24 02:27:24 +0800] [92265] [INFO] Booting worker with pid: 92265
[2022-05-24 02:27:24 +0800] [92266] [INFO] Booting worker with pid: 92266
[2022-05-24 02:27:24 +0800] [92267] [INFO] Booting worker with pid: 92267
[2022-05-24 02:27:24 +0800] [92268] [INFO] Booting worker with pid: 92268
[2022-05-24 02:27:24 +0800] [92269] [INFO] Booting worker with pid: 92269
[2022-05-24 02:27:24 +0800] [92270] [INFO] Booting worker with pid: 92270
[2022-05-24 02:27:24 +0800] [92271] [INFO] Booting worker with pid: 92271
[2022-05-24 02:27:24 +0800] [92272] [INFO] Booting worker with pid: 92272
[2022-05-24 02:27:24 +0800] [92273] [INFO] Booting worker with pid: 92273
[2022-05-24 02:27:24 +0800] [92274] [INFO] Booting worker with pid: 92274
[2022-05-24 02:27:24 +0800] [92275] [INFO] Booting worker with pid: 92275
[2022-05-24 02:27:24 +0800] [92276] [INFO] Booting worker with pid: 92276
[2022-05-24 02:27:24 +0800] [92277] [INFO] Booting worker with pid: 92277
[2022-05-24 02:27:24 +0800] [92278] [INFO] Booting worker with pid: 92278
[2022-05-24 02:27:24 +0800] [92279] [INFO] Booting worker with pid: 92279
[2022-05-24 02:27:24 +0800] [92280] [INFO] Booting worker with pid: 92280
[2022-05-24 02:27:32 +0800] [92256] [INFO] Started server process [92256]
[2022-05-24 02:27:32 +0800] [92256] [INFO] Waiting for application startup.
[2022-05-24 02:27:32 +0800] [92256] [INFO] Application startup complete.
[2022-05-24 02:27:32 +0800] [92257] [INFO] Started server process [92257]
[2022-05-24 02:27:32 +0800] [92257] [INFO] Waiting for application startup.
[2022-05-24 02:27:32 +0800] [92257] [INFO] Application startup complete.
[2022-05-24 02:27:32 +0800] [92258] [INFO] Started server process [92258]
[2022-05-24 02:27:32 +0800] [92258] [INFO] Waiting for application startup.
[2022-05-24 02:27:32 +0800] [92258] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92259] [INFO] Started server process [92259]
[2022-05-24 02:27:33 +0800] [92259] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92259] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92260] [INFO] Started server process [92260]
[2022-05-24 02:27:33 +0800] [92260] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92260] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92261] [INFO] Started server process [92261]
[2022-05-24 02:27:33 +0800] [92261] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92261] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92262] [INFO] Started server process [92262]
[2022-05-24 02:27:33 +0800] [92262] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92262] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92263] [INFO] Started server process [92263]
[2022-05-24 02:27:33 +0800] [92263] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92263] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92266] [INFO] Started server process [92266]
[2022-05-24 02:27:33 +0800] [92266] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92266] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92264] [INFO] Started server process [92264]
[2022-05-24 02:27:33 +0800] [92264] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92264] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92265] [INFO] Started server process [92265]
[2022-05-24 02:27:33 +0800] [92265] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92265] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92267] [INFO] Started server process [92267]
[2022-05-24 02:27:33 +0800] [92267] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92267] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92268] [INFO] Started server process [92268]
[2022-05-24 02:27:33 +0800] [92268] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92268] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92269] [INFO] Started server process [92269]
[2022-05-24 02:27:33 +0800] [92269] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92269] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92270] [INFO] Started server process [92270]
[2022-05-24 02:27:33 +0800] [92270] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92270] [INFO] Application startup complete.
[2022-05-24 02:27:33 +0800] [92271] [INFO] Started server process [92271]
[2022-05-24 02:27:33 +0800] [92271] [INFO] Waiting for application startup.
[2022-05-24 02:27:33 +0800] [92271] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92272] [INFO] Started server process [92272]
[2022-05-24 02:27:34 +0800] [92275] [INFO] Started server process [92275]
[2022-05-24 02:27:34 +0800] [92272] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92275] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92272] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92275] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92273] [INFO] Started server process [92273]
[2022-05-24 02:27:34 +0800] [92273] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92273] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92276] [INFO] Started server process [92276]
[2022-05-24 02:27:34 +0800] [92276] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92276] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92274] [INFO] Started server process [92274]
[2022-05-24 02:27:34 +0800] [92274] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92274] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92278] [INFO] Started server process [92278]
[2022-05-24 02:27:34 +0800] [92278] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92278] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92277] [INFO] Started server process [92277]
[2022-05-24 02:27:34 +0800] [92277] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92277] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92280] [INFO] Started server process [92280]
[2022-05-24 02:27:34 +0800] [92280] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92280] [INFO] Application startup complete.
[2022-05-24 02:27:34 +0800] [92279] [INFO] Started server process [92279]
[2022-05-24 02:27:34 +0800] [92279] [INFO] Waiting for application startup.
[2022-05-24 02:27:34 +0800] [92279] [INFO] Application startup complete.
[2022-05-24 02:27:45 +0800] [92256] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 18, in score_v1
    res = ml_score_v1(data)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/api.py", line 22, in ml_score_v1
    res = lgbMl.predict(data)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/lgb_predict.py", line 86, in predict
    tf2vec_df = self.tf2vec_feat(app_df=app_df)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/utils/decorator.py", line 18, in wrapper
    res = func(*args,**kwargs)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 71, in tf2vec_feat
    w2vec_app_df = self.__app2vec_feat(app_df)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 61, in __app2vec_feat
    df = self.__app2vec_transform(sentences)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 84, in __app2vec_transform
    vector_list_temp = [self.app2vec.wv[k] for k in sentences if k in self.app2vec.wv]
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 84, in <listcomp>
    vector_list_temp = [self.app2vec.wv[k] for k in sentences if k in self.app2vec.wv]
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 418, in __contains__
    return word in self.vocab
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'vocab'
[2022-05-24 02:29:23 +0800] [92279] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/routers/ml_router.py", line 18, in score_v1
    res = ml_score_v1(data)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/api.py", line 22, in ml_score_v1
    res = lgbMl.predict(data)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/lgb_predict.py", line 86, in predict
    tf2vec_df = self.tf2vec_feat(app_df=app_df)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/utils/decorator.py", line 18, in wrapper
    res = func(*args,**kwargs)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 71, in tf2vec_feat
    w2vec_app_df = self.__app2vec_feat(app_df)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 61, in __app2vec_feat
    df = self.__app2vec_transform(sentences)
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 84, in __app2vec_transform
    vector_list_temp = [self.app2vec.wv[k] for k in sentences if k in self.app2vec.wv]
  File "/Users/huangsir/desktop/dug/埃及/模型/dc_ml_app/app/app/v4/tf_vec.py", line 84, in <listcomp>
    vector_list_temp = [self.app2vec.wv[k] for k in sentences if k in self.app2vec.wv]
  File "/Users/huangsir/opt/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 418, in __contains__
    return word in self.vocab
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'vocab'
